sudo: false
language: erlang
otp_release:
  - "19.3"
  - "20.3"
cache:
  directories:
  - $HOME/otp/19.3
  - $HOME/otp/20.3
  - $HOME/.cache/rebar3
install: "true"
script: "make travis"
branches:
  only:
    - master
    - develop
notifications:
  email:
    - pj@ezgr.net
